New tests for irm, test
Midas-Protocol/monorepo pull request #237
Opened 2022-06-17 12:33 UTC by dezine2dev

## Description

Unit tests for SDK fuse and irm

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [x] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

2022-06-20 15:19 UTC, carlomazzaferro commented
Make sure to merge with development so we can see the CI checks @dezine2dev

2022-06-21 11:33 UTC, carlomazzaferro requested changes
Run linting, otherwise this looks good to me

2022-06-21 11:34 UTC, carlomazzaferro commented on packages/sdk/tests/new/Fuse/irm/DAIInterestRateModelV2.spec.ts
> +import { BigNumber, constants, Contract, providers } from "ethers";
We don't really need this test, as we don't ever use the DAI IRM

2022-06-21 11:34 UTC, carlomazzaferro commented on packages/sdk/tests/new/Fuse/irm/DAIInterestRateModelV2.spec.ts
> +import { BigNumber, constants, Contract, providers } from "ethers";
We can keep it however

2022-06-21 12:23 UTC, dezine2dev commented
> 

Updated lint issue.
Now I see hardhat issue which occurs in development as well

2022-06-23 04:50 UTC, carlomazzaferro commented on packages/sdk/tests-mocha/Fuse/index.spec.ts
> +        getAllPools: stub().resolves({ length: 2 }),
Nice one!

2022-06-23 04:51 UTC, carlomazzaferro commented
Awesome work @dezine2dev !

2022-06-23 04:51 UTC, carlomazzaferro approved these changes

2022-06-23 05:47 UTC, merged