wombex oracle deploy script added.
Midas-Protocol/monorepo pull request #993
Opened 2022-11-10 13:29 UTC by coolnft

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2022-11-10 14:18 UTC, vminkov requested changes

2022-11-10 14:19 UTC, carlomazzaferro commented on packages/sdk/chainDeploy/mainnets/bsc.ts
> +  // Wombex Lp Token Price Oracle
change name to wombat

2022-11-11 06:48 UTC, vminkov requested changes

2022-11-11 06:48 UTC, vminkov commented on packages/sdk/chainDeploy/mainnets/bsc.ts
> +    args: [mpo.address],
please remove the `mpo.address` param and the ` waitConfirmations: 1,` config line

2022-11-11 13:32 UTC, carlomazzaferro commented on packages/sdk/chainDeploy/mainnets/bsc.ts
> +
nitpick: standarize spacing, & casing as in the other comment

2022-11-11 13:37 UTC, carlomazzaferro approved these changes

2022-11-11 14:24 UTC, carlomazzaferro commented on packages/chains/src/bsc/assets.ts
> +    extraDocs: defaultDocs("https://bscscan.com", WOMBATLP_WBNB),
Let's add custom docs that point to the BNB LP on Wombat

2022-11-11 15:21 UTC, carlomazzaferro approved these changes

2022-11-11 15:56 UTC, merged